EN el action aparece este error ``` Run npm run build
> nextn@0.1.0 build
> next build && next export

⚠ No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

   ▲ Next.js 15.3.1

   Creating an optimized production build ...
 ✓ Compiled successfully in 8.0s
   Linting and checking validity of types ...
   Collecting page data ...
   Generating static pages (0/4) ...
   Generating static pages (1/4)
   Generating static pages (2/4)
   Generating static pages (3/4)
 ✓ Generating static pages (4/4)
   Finalizing page optimization ...
   Collecting build traces ...
   Exporting (0/3) ...
 ✓ Exporting (3/3)

Route (pages)                                 Size  First Load JS
┌ ○ / (475 ms)                              180 kB         283 kB
├   /_app                                      0 B         103 kB
└ ○ /404                                     190 B         103 kB
+ First Load JS shared by all               112 kB
  ├ chunks/framework-f8ef4a700db076da.js   44.8 kB
  ├ chunks/main-48abf604c1024050.js        39.4 kB
  ├ chunks/pages/_app-31da280848f8c835.js  17.2 kB
  └ other shared chunks (total)            10.6 kB

○  (Static)  prerendered as static content

 ⨯
    `next export` has been removed in favor of 'output: export' in next.config.js.
Learn more: https://nextjs.org/docs/app/building-your-application/deploying/static-exports

Error: Process completed with exit code 1.
```
Corrige para que pueda ejecutar con githubaction y desplegarlo en githubpages